### ISSUE TITLE
return %FlattenString(s) with object error

### ISSUE THREAD

**Issue by WarmVissarutRonaldoDude** [davidmarkclements/flatstr#4]
*Version 1.0.6*

As it's dependency of pino sometime seem pino pass Object instead of String type and it will cause error from this line : https://github.com/pinojs/pino/blob/2a3857999b27e4f9436ea1d4505ffa6b882b019f/pino.js#L222

Seem with this change
https://github.com/davidmarkclements/flatstr/commit/a350fa28e2312fdf1fc94b46db9254cc2058f978
make flatstr to doesn't support flatstr(obj) anymore as it's using `%FlattenString(s)` instead.

Test with previously version (1.0.5) it's can parse object into string (As it's simple call with Number(s))

*Node Test Version*
6.9.4
8.9.0
10.0.0

**Comment by mcollina** [comment]
What error are you getting?

**Comment by davidmarkclements** [comment]
Ahhh we need to add a typeof check to flatstr 

I'll do it as a patch update to flatstr

**Comment by davidmarkclements** [comment]
Fixed on 1.0.7

**Comment by davidmarkclements** [comment]
Thank you!

**Comment by WarmVissarutRonaldoDude** [comment]
Cool!
