### ISSUE TITLE
No actual flattening happens

### ISSUE THREAD

**Issue by vitaly-t** [davidmarkclements/flatstr#8]
See this question + answer: https://stackoverflow.com/questions/56143984/strange-node-js-performance.

Using  `flatstr(text)` has absolutely zero effect, while doing `text.match(/\n/g);` boosts performance by 35% in my tests. The latter flattens the text as a side effect.

This tells me that the library doesn't really flatten the string.

Tested in:

* Node.js v10.15.3
* Windows 10

**Comment by davidmarkclements** [comment]
what happens if you run the benchmarks in this repo? do you get the same numbers?

**Comment by davidmarkclements** [comment]
if I replace the exported function with the regex approach, the benchmarks are the same as with flatstr. It may be that in your setup it's setting flatstr here https://github.com/davidmarkclements/flatstr/blob/master/index.js#L23 instead of here https://github.com/davidmarkclements/flatstr/blob/master/index.js#L8 - which is why it would be interesting to see if you get similar results in the benchmarks or not.

If there's no diff in the benchmarks then its a Windows problem. If there is a diff, then it might be due to some internal architecture thing.. maybe something taking over initialization of process etc. This would still be good to figure out a workaround to.

**Comment by vitaly-t** [comment]
Are you using Node.js v10.15.3?

**Comment by davidmarkclements** [comment]
yes
macOs

**Comment by davidmarkclements** [comment]
using flatstr:

![image](https://user-images.githubusercontent.com/1190716/57860802-cbb76f00-77f5-11e9-86bd-8e10c7ffa419.png)



using match:
![image](https://user-images.githubusercontent.com/1190716/57860628-7b401180-77f5-11e9-9fad-e4fccb8c937d.png)

**Comment by davidmarkclements** [comment]
the difference used to be much more significant, in Node 6/8. Over time V8 has become better at handling these cases.

**Comment by vitaly-t** [comment]
So, I've just cloned it, and tried to run `benchmark.js` and `alt-benchmark.js`, but none work for me...

```
D:\NodeJS\tmp\flatstr>node benchmark.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'D:\dev\null'
```

and

```
D:\NodeJS\tmp\flatstr>node alt-benchmark.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'D:\dev\null'
```
any idea why?

**Comment by davidmarkclements** [comment]
1. try running the benchmarks, see if theres a diff

2. try running your own process/benchmark with --allow-natives-syntax flag, and use the following:
```js
var flatstr = Function('s', 'return typeof s === "string" ? %FlattenString(s) : s')
flatstr(text)
```

3. `console.log(require('flatstr'))` where it is you're using, what function does it contain? what about after you call it a few times?

**Comment by davidmarkclements** [comment]
ah hahah yes that will be this line in benchmark
https://github.com/davidmarkclements/flatstr/blob/master/benchmark.js

if you try those things above I'll see if I can update benchmark to be cross platform

**Comment by vitaly-t** [comment]
Ok, got it working...

```
D:\NodeJS\tmp\flatstr>node benchmark.js
unflattenedManySmallConcats*10000: 67.367ms
flattenedManySmallConcats*10000: 59.934ms
unflattenedSeveralLargeConcats*10000: 306.749ms
flattenedSeveralLargeConcats*10000: 293.969ms
unflattenedExponentialSmallConcats*10000: 66.097ms
flattenedExponentialSmallConcats*10000: 72.241ms
unflattenedExponentialLargeConcats*10000: 2371.896ms
flattenedExponentialLargeConcats*10000: 2653.211ms
unflattenedManySmallConcats*10000: 39.990ms
flattenedManySmallConcats*10000: 39.218ms
unflattenedSeveralLargeConcats*10000: 430.371ms
flattenedSeveralLargeConcats*10000: 332.246ms
unflattenedExponentialSmallConcats*10000: 90.190ms
flattenedExponentialSmallConcats*10000: 99.194ms
unflattenedExponentialLargeConcats*10000: 4194.583ms
flattenedExponentialLargeConcats*10000: 3186.723ms
```

**Comment by vitaly-t** [comment]
Ok, I gave up waiting for the other one to finish, it is taking too long, here's the top results from it...

```
D:\NodeJS\tmp\flatstr>node alt-benchmark.js
alt0ManySmallConcats*10000: 61.016ms
alt1ManySmallConcats*10000: 52.333ms
alt2ManySmallConcats*10000: 67.571ms
alt3ManySmallConcats*10000: 59.650ms
alt4ManySmallConcats*10000: 82.685ms
alt5ManySmallConcats*10000: 94.738ms
alt6ManySmallConcats*10000: 68.723ms
alt7ManySmallConcats*10000: 70.347ms
alt8ManySmallConcats*10000: 85.376ms
alt9ManySmallConcats*10000: 114.013ms
alt0SeveralLargeConcats*10000: 675.257ms
alt1SeveralLargeConcats*10000: 366.713ms
alt2SeveralLargeConcats*10000: 371.997ms
alt3SeveralLargeConcats*10000: 315.530ms
alt4SeveralLargeConcats*10000: 314.062ms
alt5SeveralLargeConcats*10000: 1416.722ms
alt6SeveralLargeConcats*10000: 349.437ms
alt7SeveralLargeConcats*10000: 294.481ms
alt8SeveralLargeConcats*10000: 280.092ms
alt9SeveralLargeConcats*10000: 290.051ms
alt0ExponentialSmallConcats*10000: 107.311ms
alt1ExponentialSmallConcats*10000: 75.602ms
alt2ExponentialSmallConcats*10000: 75.318ms
alt3ExponentialSmallConcats*10000: 76.328ms
alt4ExponentialSmallConcats*10000: 65.689ms
alt5ExponentialSmallConcats*10000: 150.986ms
alt6ExponentialSmallConcats*10000: 73.806ms
alt7ExponentialSmallConcats*10000: 62.622ms
alt8ExponentialSmallConcats*10000: 69.816ms
alt9ExponentialSmallConcats*10000: 128.308ms
alt0ExponentialLargeConcats*10000: 2764.222ms
alt1ExponentialLargeConcats*10000: 2963.397ms
alt2ExponentialLargeConcats*10000: 3094.134ms
alt3ExponentialLargeConcats*10000: 3810.735ms
alt4ExponentialLargeConcats*10000: 4164.587ms
alt5ExponentialLargeConcats*10000: 18238.227ms
alt6ExponentialLargeConcats*10000: 4288.991ms
alt7ExponentialLargeConcats*10000: 3183.052ms
alt8ExponentialLargeConcats*10000: 3893.190ms
alt9ExponentialLargeConcats*10000: 3755.796ms
alt0ManySmallConcats*10000: 43.267ms
alt1ManySmallConcats*10000: 42.418ms
alt2ManySmallConcats*10000: 50.999ms
alt3ManySmallConcats*10000: 39.975ms
alt4ManySmallConcats*10000: 41.135ms
alt5ManySmallConcats*10000: 54.565ms
alt6ManySmallConcats*10000: 40.455ms
alt7ManySmallConcats*10000: 42.771ms
alt8ManySmallConcats*10000: 57.727ms
alt9ManySmallConcats*10000: 44.125ms
alt0SeveralLargeConcats*10000: 608.369ms
alt1SeveralLargeConcats*10000: 720.251ms
alt2SeveralLargeConcats*10000: 778.405ms
alt3SeveralLargeConcats*10000: 796.114ms
alt4SeveralLargeConcats*10000: 675.070ms
alt5SeveralLargeConcats*10000: 2475.093ms
alt6SeveralLargeConcats*10000: 732.138ms
alt7SeveralLargeConcats*10000: 744.026ms
alt8SeveralLargeConcats*10000: 784.989ms
```

**Comment by davidmarkclements** [comment]
cool.. .your small concats are really fast.. which is weird - maybe its the nul device on windows, btw does this work https://github.com/davidmarkclements/flatstr/commit/869e4a3caa05faf494015e3afe4e18c0dc8b217c

**Comment by davidmarkclements** [comment]
oh right - yeah don't worry about alt - if you look at the bottom of the file it's just testing other ways of flattening.

the benchmark file test flatstr itself

it looks like flatenning is happening on Windows. So it may be to do with the way your process is setup

Does this make any difference for you:

> try running your own process/benchmark with --allow-natives-syntax flag, and use the following:
> var flatstr = Function('s', 'return typeof s === "string" ? %FlattenString(s) : s')
> flatstr(text)

also what about the output of this:

> console.log(require('flatstr')) where it is you're using, what function does it contain? what about after you call it a few times?

**Comment by vitaly-t** [comment]
> does this work 869e4a3

Yes, it does work too. Before I simply had to create `dev` on the D drive.

**Comment by vitaly-t** [comment]
Have done all that, still no effect.... i.e. passing in parameter `--allow-natives-syntax` and using that code.

**Comment by davidmarkclements** [comment]
what's the output of `console.log(require('flatstr'))`

**Comment by vitaly-t** [comment]
`[Function: anonymous]`

or wait,...the original? - 

`[Function: flatstr]`

**Comment by davidmarkclements** [comment]
sorry `console.log(require('flatstr') + '')`

**Comment by vitaly-t** [comment]
```js
(s) => {
        try {
          return _flatstr(s)
        } catch (e) {
          v8.setFlagsFromString('--allow-natives-syntax')
          _flatstr = Function('s', 'return typeof s === "string" ? %FlattenString(s) : s')
          v8.setFlagsFromString('--no-allow-natives-syntax')
          return s
        }
      }
```

**Comment by davidmarkclements** [comment]
ok - and you logged this from the exact same place that you're using `text.match`?

**Comment by vitaly-t** [comment]
yes.

**Comment by davidmarkclements** [comment]
cool. ok now in the same place

```
const flatstr = require('flatstr')
var i = 1000
while (i--) { flatstr('abc') }
debugger
flatstr('abc')
```

run with --node-inspect and when you reach the debugger break point, step into final flatstr function and step through it, see if goes into the try block or the catch block

**Comment by davidmarkclements** [comment]
if it goes into the catch block that will explain why you're seeing no perf increase. It means for some reason `v8.setFlagsFromString('--allow-natives-syntax')` isn't working in your situation. But remember it works in the benchmarks. Even if we set it to use text.match (which also carries slightly more overhead that use `%FlattenString`) - it still won't flatten in Node 12

**Comment by vitaly-t** [comment]
Having difficulty following it...

If I debug without `--node-inspect`, my WebStorm refuses to break on the breakpoint, and without the flag it breaks, and the last line takes me to this code:

```js
(function anonymous(s
) {
return typeof s === "string" ? %FlattenString(s) : s
})
```

Anyhow, I'm off for today, will check back tomorrow. Thank you for the help!!!!

**Comment by davidmarkclements** [comment]
I've just been studying the alts. It looks like the alt3 method is faster that the current solution in both 10 and 12 - expect a patch update.

**Comment by davidmarkclements** [comment]
should be closed by https://github.com/davidmarkclements/flatstr/commit/543c4513bbd490a9eb2b797419f1fd4240adb190#diff-168726dbe96b3ce427e7fedce31bb0bcR3

**Comment by vitaly-t** [comment]
Wait, what? You've just removed everything? :smile: :smile: :smile:

**Comment by davidmarkclements** [comment]
Hahahaha yes. Mostly the code was hedging against flat string operation
being removed from v8 engines in future Node versions for whatever method
we use - but it was clearly causing more trouble than it’s worth. The alt
benchmarks show that the new method is consistently for all versions
(although slightly slower in Node 8 case, but since that’s coming to eol in
Oct it’s fine)

**Comment by songkeys** [comment]
Hi. I don't find the new version has significant benefits over the unflatten one as stated in the README. Is this expected? Is it still encourage to use this strategy in production?

node 14

```
unflattenedManySmallConcats*10000: 163.703ms
flattenedManySmallConcats*10000: 119.053ms
unflattenedSeveralLargeConcats*10000: 237.501ms
flattenedSeveralLargeConcats*10000: 271.777ms
unflattenedExponentialSmallConcats*10000: 143.353ms
flattenedExponentialSmallConcats*10000: 142.437ms
unflattenedExponentialLargeConcats*10000: 3.245s
flattenedExponentialLargeConcats*10000: 3.192s
unflattenedManySmallConcats*10000: 112.904ms
flattenedManySmallConcats*10000: 121.96ms
unflattenedSeveralLargeConcats*10000: 247.027ms
flattenedSeveralLargeConcats*10000: 242.5ms
unflattenedExponentialSmallConcats*10000: 142.669ms
flattenedExponentialSmallConcats*10000: 136.87ms
unflattenedExponentialLargeConcats*10000: 3.140s
flattenedExponentialLargeConcats*10000: 3.146s
```

node 12

```
unflattenedManySmallConcats*10000: 144.137ms
flattenedManySmallConcats*10000: 110.902ms
unflattenedSeveralLargeConcats*10000: 241.327ms
flattenedSeveralLargeConcats*10000: 224.183ms
unflattenedExponentialSmallConcats*10000: 110.130ms
flattenedExponentialSmallConcats*10000: 99.172ms
unflattenedExponentialLargeConcats*10000: 3346.660ms
flattenedExponentialLargeConcats*10000: 3231.309ms
unflattenedManySmallConcats*10000: 109.325ms
flattenedManySmallConcats*10000: 108.757ms
unflattenedSeveralLargeConcats*10000: 219.939ms
flattenedSeveralLargeConcats*10000: 200.380ms
unflattenedExponentialSmallConcats*10000: 177.994ms
flattenedExponentialSmallConcats*10000: 120.325ms
unflattenedExponentialLargeConcats*10000: 2813.259ms
flattenedExponentialLargeConcats*10000: 2929.145ms
```

node 10

```
unflattenedManySmallConcats*10000: 147.906ms
flattenedManySmallConcats*10000: 102.184ms
unflattenedSeveralLargeConcats*10000: 251.802ms
flattenedSeveralLargeConcats*10000: 214.785ms
unflattenedExponentialSmallConcats*10000: 107.674ms
flattenedExponentialSmallConcats*10000: 125.697ms
unflattenedExponentialLargeConcats*10000: 1769.868ms
flattenedExponentialLargeConcats*10000: 1848.486ms
unflattenedManySmallConcats*10000: 104.814ms
flattenedManySmallConcats*10000: 114.008ms
unflattenedSeveralLargeConcats*10000: 225.411ms
flattenedSeveralLargeConcats*10000: 210.955ms
unflattenedExponentialSmallConcats*10000: 104.281ms
flattenedExponentialSmallConcats*10000: 105.947ms
unflattenedExponentialLargeConcats*10000: 1712.176ms
flattenedExponentialLargeConcats*10000: 1744.395ms
```

---

update: I've checked that fastify is [still using it](https://github.com/fastify/fastify/blob/43ea177527d535cc17ed168dd479e07cc61db19d/lib/reply.js#L351). I don't understand. As the benchmark shows, `flatStr` even has worse performance in some cases.

**Comment by mcollina** [comment]
I've tried removing this a few times already, and Fastify and Pino benchmarks always worsen because of it, at least in Node v12. I _think_ this is not needed anymore in v14+ from the look of it.
